/**
 * generate-sitemap.mjs
 *
 * Generates public/sitemap.xml by combining:
 *   1. Static pages (homepage, /trade, /library) — all 4 locales
 *   2. Top N card permalink pages from the Supabase trending cards RPC
 *
 * Usage:
 *   node scripts/generate-sitemap.mjs
 *   node scripts/generate-sitemap.mjs --limit 500
 */

import { createClient } from "@supabase/supabase-js";
import { writeFile } from "node:fs/promises";
import { resolve, dirname } from "node:path";
import { fileURLToPath } from "node:url";

const __dirname = dirname(fileURLToPath(import.meta.url));
const OUT = resolve(__dirname, "../public/sitemap.xml");

const SUPABASE_URL = "https://sxteuctysfiwripnaozi.supabase.co";
const SUPABASE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InN4dGV1Y3R5c2Zpd3JpcG5hb3ppIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTczNTA1OTAsImV4cCI6MjA3MjkyNjU5MH0.nrRXz20dGkNH3wDIkHTxlrVMC-uvEiukWsq9-Pu4Lcw";

const LOCALES   = ["en", "fr", "de", "it"];
const BASE      = "https://0nefor.one";
const TODAY     = new Date().toISOString().slice(0, 10);
const LIMIT     = parseInt(process.argv.find(a => a.startsWith("--limit="))?.split("=")[1] ?? "200", 10);

// ── Helpers ───────────────────────────────────────────────────────────────────

function hreflangSet(path) {
  const alts = LOCALES.map(l =>
    `    <xhtml:link rel="alternate" hreflang="${l}"        href="${BASE}/${l}${path}"/>`
  ).join("\n");
  return alts + `\n    <xhtml:link rel="alternate" hreflang="x-default" href="${BASE}/en${path}"/>`;
}

function urlEntry({ path, changefreq, priority }) {
  return LOCALES.map(locale => `
  <url>
    <loc>${BASE}/${locale}${path}</loc>
${hreflangSet(path)}
    <lastmod>${TODAY}</lastmod>
    <changefreq>${changefreq}</changefreq>
    <priority>${locale === "en" ? priority : (priority - 0.1).toFixed(1)}</priority>
  </url>`).join("");
}

// ── Static pages ──────────────────────────────────────────────────────────────

// Only include publicly useful pages — auth-required pages (library, trade, account)
// show thin/empty content to Googlebot and waste crawl budget.
const STATIC_PAGES = [
  { path: "/", changefreq: "daily", priority: 1.0 },
];

// ── Fetch trending cards from Supabase ────────────────────────────────────────

async function fetchTopCards(limit) {
  const supabase = createClient(SUPABASE_URL, SUPABASE_KEY);

  console.log(`Fetching top ${limit} traded cards from Supabase...`);

  // Try the trending RPC first (returns image_id + trade_count)
  const { data: rpcData, error: rpcErr } = await supabase
    .rpc("get_trending_cards", { p_limit: limit });

  if (!rpcErr && rpcData?.length) {
    console.log(`  Got ${rpcData.length} cards from get_trending_cards RPC`);
    return rpcData.map(r => ({ image_id: r.image_id, name: r.name }));
  }

  // Fallback: count distinct image_ids from the Card table directly
  console.log("  RPC unavailable, falling back to Card table query...");
  const { data, error } = await supabase
    .from("Card")
    .select("image_id, name")
    .not("status", "in", '("traded","locked")')
    .eq("wish", false)
    .not("image_id", "is", null)
    .limit(limit * 3); // fetch more to deduplicate

  if (error) {
    console.error("  Supabase query failed:", error.message);
    return [];
  }

  // Deduplicate by image_id, keep first occurrence
  const seen = new Set();
  const deduped = [];
  for (const row of data) {
    if (!seen.has(row.image_id)) {
      seen.add(row.image_id);
      deduped.push(row);
      if (deduped.length >= limit) break;
    }
  }
  console.log(`  Got ${deduped.length} unique cards from Card table`);
  return deduped;
}

// ── Build sitemap ─────────────────────────────────────────────────────────────

async function main() {
  const cards = await fetchTopCards(LIMIT);

  const staticEntries  = STATIC_PAGES.map(urlEntry).join("");
  const cardEntries    = cards.map(c =>
    urlEntry({ path: `/card/${c.image_id}`, changefreq: "weekly", priority: 0.6 })
  ).join("");

  const xml = `<?xml version="1.0" encoding="UTF-8"?>
<!--
  Auto-generated by scripts/generate-sitemap.mjs
  ${new Date().toISOString()}
  Static pages: ${STATIC_PAGES.length} × ${LOCALES.length} locales
  Card pages:   ${cards.length} × ${LOCALES.length} locales
  Total <url> entries: ${(STATIC_PAGES.length + cards.length) * LOCALES.length}
-->
<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9"
        xmlns:xhtml="http://www.w3.org/1999/xhtml">
${staticEntries}
${cardEntries}
</urlset>
`;

  await writeFile(OUT, xml, "utf8");
  console.log(`\nWrote ${OUT}`);
  console.log(`  ${STATIC_PAGES.length} static pages × ${LOCALES.length} locales = ${STATIC_PAGES.length * LOCALES.length} entries`);
  console.log(`  ${cards.length} card pages × ${LOCALES.length} locales = ${cards.length * LOCALES.length} entries`);
  console.log(`  Total: ${(STATIC_PAGES.length + cards.length) * LOCALES.length} <url> entries`);
}

main().catch(err => { console.error(err); process.exit(1); });
