/**
 * Major cities by ISO 3166-1 alpha-2 country code.
 * Used to populate the city autocomplete in Account.vue.
 * Users can still type any city not in the list (v-combobox).
 */
export const CITIES_BY_COUNTRY = {
  AD: ['Andorra la Vella', 'Escaldes-Engordany', 'Sant Julià de Lòria'],
  AE: ['Abu Dhabi', 'Dubai', 'Sharjah', 'Al Ain', 'Ajman', 'Ras al-Khaimah'],
  AF: ['Kabul', 'Kandahar', 'Herat', 'Mazar-i-Sharif', 'Jalalabad'],
  AL: ['Tirana', 'Durrës', 'Vlorë', 'Shkodër', 'Elbasan'],
  AM: ['Yerevan', 'Gyumri', 'Vanadzor'],
  AO: ['Luanda', 'Huambo', 'Lobito', 'Benguela'],
  AR: ['Buenos Aires', 'Córdoba', 'Rosario', 'Mendoza', 'La Plata', 'Tucumán', 'Mar del Plata', 'Salta', 'Santa Fe', 'San Juan'],
  AT: ['Vienna', 'Graz', 'Linz', 'Salzburg', 'Innsbruck', 'Klagenfurt', 'Villach', 'Wels', 'St. Pölten'],
  AU: ['Sydney', 'Melbourne', 'Brisbane', 'Perth', 'Adelaide', 'Gold Coast', 'Newcastle', 'Canberra', 'Wollongong', 'Hobart', 'Geelong', 'Townsville', 'Darwin'],
  AZ: ['Baku', 'Ganja', 'Sumqayıt', 'Mingəçevir'],
  BA: ['Sarajevo', 'Banja Luka', 'Mostar', 'Tuzla', 'Zenica'],
  BD: ['Dhaka', 'Chittagong', 'Khulna', 'Rajshahi', 'Sylhet', 'Comilla'],
  BE: ['Brussels', 'Antwerp', 'Ghent', 'Liège', 'Bruges', 'Namur', 'Mons', 'Leuven', 'Charleroi'],
  BF: ['Ouagadougou', 'Bobo-Dioulasso', 'Koudougou'],
  BG: ['Sofia', 'Plovdiv', 'Varna', 'Burgas', 'Ruse', 'Stara Zagora', 'Pleven'],
  BH: ['Manama', 'Riffa', 'Muharraq'],
  BJ: ['Cotonou', 'Porto-Novo', 'Parakou'],
  BN: ['Bandar Seri Begawan', 'Kuala Belait', 'Seria'],
  BO: ['La Paz', 'Santa Cruz de la Sierra', 'Cochabamba', 'Sucre', 'Oruro'],
  BR: ['São Paulo', 'Rio de Janeiro', 'Brasília', 'Salvador', 'Fortaleza', 'Belo Horizonte', 'Manaus', 'Curitiba', 'Recife', 'Porto Alegre', 'Goiânia', 'Belém', 'Guarulhos', 'Campinas', 'Natal', 'Maceió', 'São Luís', 'Teresina', 'Campo Grande', 'João Pessoa'],
  BS: ['Nassau', 'Freeport'],
  BT: ['Thimphu', 'Phuntsholing'],
  BW: ['Gaborone', 'Francistown', 'Molepolole'],
  BY: ['Minsk', 'Homiel', 'Vitebsk', 'Hrodna', 'Brest', 'Mahilyow'],
  BZ: ['Belmopan', 'Belize City'],
  CA: ['Toronto', 'Montreal', 'Vancouver', 'Calgary', 'Edmonton', 'Ottawa', 'Winnipeg', 'Quebec City', 'Hamilton', 'Kitchener', 'London', 'Halifax', 'Oshawa', 'Victoria', 'Windsor', 'Saskatoon', 'Regina', 'Sherbrooke', 'St. John\'s'],
  CD: ['Kinshasa', 'Lubumbashi', 'Mbuji-Mayi', 'Kananga', 'Kisangani'],
  CF: ['Bangui', 'Bimbo'],
  CG: ['Brazzaville', 'Pointe-Noire', 'Dolisie'],
  CH: ['Zurich', 'Geneva', 'Basel', 'Bern', 'Lausanne', 'Winterthur', 'Lucerne', 'St. Gallen', 'Lugano', 'Biel/Bienne', 'Thun', 'Köniz', 'La Chaux-de-Fonds'],
  CL: ['Santiago', 'Valparaíso', 'Concepción', 'Antofagasta', 'Viña del Mar', 'Temuco', 'Rancagua', 'Talca', 'Iquique', 'Puerto Montt'],
  CM: ['Yaoundé', 'Douala', 'Garoua', 'Bamenda', 'Bafoussam'],
  CN: ['Shanghai', 'Beijing', 'Chongqing', 'Guangzhou', 'Shenzhen', 'Tianjin', 'Wuhan', 'Chengdu', 'Nanjing', 'Xi\'an', 'Hangzhou', 'Shenyang', 'Harbin', 'Qingdao', 'Jinan', 'Dalian', 'Zhengzhou', 'Changsha', 'Kunming', 'Xiamen'],
  CO: ['Bogotá', 'Medellín', 'Cali', 'Barranquilla', 'Cartagena', 'Cúcuta', 'Bucaramanga', 'Pereira', 'Manizales', 'Santa Marta'],
  CR: ['San José', 'Cartago', 'Alajuela', 'Heredia', 'Liberia'],
  CU: ['Havana', 'Santiago de Cuba', 'Camagüey', 'Holguín', 'Guantánamo'],
  CV: ['Praia', 'Mindelo'],
  CY: ['Nicosia', 'Limassol', 'Larnaca', 'Paphos', 'Famagusta'],
  CZ: ['Prague', 'Brno', 'Ostrava', 'Plzeň', 'Liberec', 'Olomouc', 'České Budějovice', 'Hradec Králové', 'Pardubice', 'Zlín'],
  DE: ['Berlin', 'Hamburg', 'Munich', 'Cologne', 'Frankfurt', 'Stuttgart', 'Düsseldorf', 'Dortmund', 'Essen', 'Leipzig', 'Bremen', 'Dresden', 'Hannover', 'Nuremberg', 'Duisburg', 'Bochum', 'Wuppertal', 'Bonn', 'Bielefeld', 'Münster', 'Karlsruhe', 'Mannheim', 'Augsburg', 'Wiesbaden', 'Mönchengladbach', 'Gelsenkirchen', 'Braunschweig', 'Kiel', 'Chemnitz', 'Aachen', 'Halle', 'Magdeburg', 'Freiburg', 'Krefeld', 'Lübeck', 'Erfurt'],
  DJ: ['Djibouti'],
  DK: ['Copenhagen', 'Aarhus', 'Odense', 'Aalborg', 'Frederiksberg', 'Esbjerg', 'Randers', 'Kolding', 'Horsens'],
  DO: ['Santo Domingo', 'Santiago de los Caballeros', 'San Pedro de Macorís', 'La Romana'],
  DZ: ['Algiers', 'Oran', 'Constantine', 'Annaba', 'Blida', 'Batna', 'Sétif', 'Sidi Bel Abbès'],
  EC: ['Quito', 'Guayaquil', 'Cuenca', 'Santo Domingo', 'Ambato', 'Portoviejo', 'Machala', 'Durán'],
  EE: ['Tallinn', 'Tartu', 'Narva', 'Pärnu'],
  EG: ['Cairo', 'Alexandria', 'Giza', 'Shubra El-Kheima', 'Port Said', 'Suez', 'Luxor', 'Mansoura', 'El-Mahalla El-Kubra', 'Tanta', 'Asyut', 'Ismailia'],
  ER: ['Asmara', 'Keren'],
  ES: ['Madrid', 'Barcelona', 'Valencia', 'Seville', 'Zaragoza', 'Málaga', 'Murcia', 'Palma', 'Las Palmas', 'Bilbao', 'Valladolid', 'Alicante', 'Córdoba', 'Vigo', 'Gijón', 'L\'Hospitalet de Llobregat', 'Badalona', 'Cartagena', 'Jerez de la Frontera', 'Granada', 'Elche', 'Oviedo', 'Badalona', 'Sabadell', 'Terrassa', 'Santa Cruz de Tenerife'],
  ET: ['Addis Ababa', 'Dire Dawa', 'Adama', 'Gondar', 'Hawassa', 'Bahir Dar', 'Mekele'],
  FI: ['Helsinki', 'Espoo', 'Tampere', 'Vantaa', 'Oulu', 'Turku', 'Jyväskylä', 'Lahti', 'Kuopio', 'Pori'],
  FJ: ['Suva', 'Lautoka', 'Nausori'],
  FR: ['Paris', 'Marseille', 'Lyon', 'Toulouse', 'Nice', 'Nantes', 'Strasbourg', 'Montpellier', 'Bordeaux', 'Lille', 'Rennes', 'Reims', 'Le Havre', 'Toulon', 'Grenoble', 'Dijon', 'Nîmes', 'Angers', 'Villeurbanne', 'Saint-Étienne', 'Clermont-Ferrand', 'Aix-en-Provence', 'Brest', 'Tours', 'Amiens', 'Limoges', 'Perpignan', 'Metz', 'Rouen', 'Besançon', 'Nancy', 'Orléans', 'Pau', 'Valenciennes', 'Mulhouse'],
  GA: ['Libreville', 'Port-Gentil', 'Franceville'],
  GB: ['London', 'Birmingham', 'Leeds', 'Glasgow', 'Sheffield', 'Bradford', 'Manchester', 'Edinburgh', 'Liverpool', 'Bristol', 'Cardiff', 'Coventry', 'Leicester', 'Belfast', 'Nottingham', 'Newcastle upon Tyne', 'Sunderland', 'Brighton', 'Plymouth', 'Derby', 'Wolverhampton', 'Southampton', 'Norwich', 'Aberdeen', 'Portsmouth', 'Milton Keynes', 'York', 'Oxford', 'Cambridge', 'Exeter', 'Dundee', 'Swansea'],
  GE: ['Tbilisi', 'Kutaisi', 'Rustavi', 'Batumi', 'Zugdidi'],
  GH: ['Accra', 'Kumasi', 'Tamale', 'Sekondi-Takoradi', 'Cape Coast'],
  GM: ['Banjul', 'Serekunda', 'Brikama'],
  GN: ['Conakry', 'N\'Zérékoré', 'Kankan'],
  GQ: ['Malabo', 'Bata'],
  GR: ['Athens', 'Thessaloniki', 'Patras', 'Piraeus', 'Larissa', 'Heraklion', 'Kallithea', 'Peristeri', 'Acharnes', 'Kalamaria', 'Volos', 'Rhodes', 'Ioannina'],
  GT: ['Guatemala City', 'Mixco', 'Villa Nueva', 'San Juan Sacatepéquez', 'Quetzaltenango'],
  GW: ['Bissau', 'Bafatá'],
  GY: ['Georgetown', 'Linden', 'New Amsterdam'],
  HK: ['Hong Kong', 'Kowloon', 'Tsuen Wan', 'Yuen Long', 'Tuen Mun', 'Sha Tin'],
  HN: ['Tegucigalpa', 'San Pedro Sula', 'Choloma', 'La Ceiba', 'El Progreso'],
  HR: ['Zagreb', 'Split', 'Rijeka', 'Osijek', 'Zadar', 'Slavonski Brod'],
  HT: ['Port-au-Prince', 'Carrefour', 'Delmas', 'Cap-Haïtien'],
  HU: ['Budapest', 'Debrecen', 'Miskolc', 'Szeged', 'Pécs', 'Győr', 'Nyíregyháza', 'Kecskemét', 'Székesfehérvár'],
  ID: ['Jakarta', 'Surabaya', 'Medan', 'Bandung', 'Bekasi', 'Palembang', 'Makassar', 'Tangerang', 'Semarang', 'Depok', 'Batam', 'Pekanbaru', 'Bandar Lampung', 'Bogor', 'Padang', 'Malang', 'Yogyakarta', 'Denpasar'],
  IE: ['Dublin', 'Cork', 'Limerick', 'Galway', 'Waterford', 'Drogheda', 'Dundalk', 'Swords', 'Bray'],
  IL: ['Jerusalem', 'Tel Aviv', 'Haifa', 'Rishon LeZion', 'Petah Tikva', 'Ashdod', 'Netanya', 'Beer Sheva', 'Holon', 'Bnei Brak', 'Ramat Gan'],
  IN: ['Mumbai', 'Delhi', 'Bangalore', 'Hyderabad', 'Chennai', 'Kolkata', 'Ahmedabad', 'Pune', 'Surat', 'Jaipur', 'Lucknow', 'Kanpur', 'Nagpur', 'Visakhapatnam', 'Indore', 'Thane', 'Bhopal', 'Pimpri-Chinchwad', 'Patna', 'Vadodara', 'Ghaziabad', 'Ludhiana', 'Agra', 'Nashik', 'Faridabad', 'Rajkot', 'Meerut', 'Varanasi', 'Srinagar', 'Amritsar', 'Allahabad', 'Howrah', 'Coimbatore', 'Chandigarh'],
  IQ: ['Baghdad', 'Basra', 'Mosul', 'Erbil', 'Sulaymaniyah', 'Kirkuk', 'Najaf'],
  IR: ['Tehran', 'Mashhad', 'Isfahan', 'Karaj', 'Tabriz', 'Shiraz', 'Ahvaz', 'Qom', 'Kermanshah', 'Urmia', 'Zahedan', 'Rasht', 'Hamadan'],
  IS: ['Reykjavik', 'Kópavogur', 'Hafnarfjörður', 'Akureyri'],
  IT: ['Rome', 'Milan', 'Naples', 'Turin', 'Palermo', 'Genoa', 'Bologna', 'Florence', 'Bari', 'Catania', 'Venice', 'Verona', 'Messina', 'Padua', 'Trieste', 'Taranto', 'Brescia', 'Parma', 'Prato', 'Modena', 'Reggio Calabria', 'Reggio Emilia', 'Perugia', 'Livorno', 'Ravenna', 'Cagliari', 'Foggia', 'Rimini', 'Salerno', 'Ferrara'],
  JM: ['Kingston', 'Montego Bay', 'Portmore', 'Spanish Town'],
  JO: ['Amman', 'Zarqa', 'Irbid', 'Russeifa', 'Wadi as-Sir', 'Aqaba'],
  JP: ['Tokyo', 'Yokohama', 'Osaka', 'Nagoya', 'Sapporo', 'Fukuoka', 'Kobe', 'Kawasaki', 'Kyoto', 'Saitama', 'Hiroshima', 'Sendai', 'Kitakyushu', 'Chiba', 'Sakai', 'Niigata', 'Hamamatsu', 'Shizuoka', 'Sagamihara', 'Okayama', 'Kumamoto', 'Kagoshima', 'Funabashi', 'Hachioji', 'Matsuyama', 'Higashiosaka'],
  KE: ['Nairobi', 'Mombasa', 'Kisumu', 'Nakuru', 'Eldoret', 'Thika'],
  KG: ['Bishkek', 'Osh', 'Jalal-Abad'],
  KH: ['Phnom Penh', 'Siem Reap', 'Sihanoukville', 'Battambang'],
  KI: ['South Tarawa'],
  KM: ['Moroni', 'Moutsamoudou'],
  KN: ['Basseterre'],
  KP: ['Pyongyang', 'Hamhung', 'Chongjin'],
  KR: ['Seoul', 'Busan', 'Incheon', 'Daegu', 'Daejeon', 'Gwangju', 'Suwon', 'Ulsan', 'Changwon', 'Seongnam', 'Goyang', 'Yongin', 'Bucheon', 'Cheongju', 'Ansan', 'Anyang', 'Jeonju'],
  KW: ['Kuwait City', 'Al Ahmadi', 'Hawalli', 'As Salimiyah'],
  KZ: ['Nur-Sultan', 'Almaty', 'Shymkent', 'Aktobe', 'Karaganda', 'Taraz', 'Pavlodar', 'Oskemen'],
  LA: ['Vientiane', 'Pakse', 'Savannakhet'],
  LB: ['Beirut', 'Tripoli', 'Sidon', 'Tyre', 'Jounieh'],
  LC: ['Castries', 'Bisee'],
  LI: ['Vaduz', 'Schaan'],
  LK: ['Colombo', 'Dehiwala-Mount Lavinia', 'Moratuwa', 'Jaffna', 'Negombo', 'Kandy'],
  LR: ['Monrovia', 'Gbarnga'],
  LS: ['Maseru', 'Teyateyaneng'],
  LT: ['Vilnius', 'Kaunas', 'Klaipėda', 'Šiauliai', 'Panevėžys'],
  LU: ['Luxembourg City', 'Esch-sur-Alzette', 'Differdange', 'Dudelange'],
  LV: ['Riga', 'Daugavpils', 'Liepāja', 'Jelgava', 'Jūrmala', 'Ventspils'],
  LY: ['Tripoli', 'Benghazi', 'Misrata', 'Bayda'],
  MA: ['Casablanca', 'Rabat', 'Fez', 'Marrakesh', 'Agadir', 'Tangier', 'Meknès', 'Oujda', 'Kenitra', 'Tétouan', 'Safi', 'Mohammédia', 'El Jadida'],
  MD: ['Chișinău', 'Tiraspol', 'Bălți', 'Bender'],
  ME: ['Podgorica', 'Nikšić', 'Herceg Novi'],
  MG: ['Antananarivo', 'Toamasina', 'Antsirabe', 'Fianarantsoa', 'Mahajanga'],
  MH: ['Majuro', 'Ebeye'],
  MK: ['Skopje', 'Bitola', 'Kumanovo', 'Ohrid'],
  ML: ['Bamako', 'Sikasso', 'Mopti', 'Ségou'],
  MM: ['Naypyidaw', 'Yangon', 'Mandalay', 'Mawlamyine', 'Bago'],
  MN: ['Ulaanbaatar', 'Erdenet', 'Darkhan'],
  MR: ['Nouakchott', 'Nouadhibou'],
  MT: ['Valletta', 'Birkirkara', 'Qormi', 'Mosta'],
  MU: ['Port Louis', 'Beau Bassin-Rose Hill', 'Vacoas-Phoenix', 'Curepipe'],
  MV: ['Malé', 'Addu City'],
  MW: ['Lilongwe', 'Blantyre', 'Mzuzu', 'Zomba'],
  MX: ['Mexico City', 'Guadalajara', 'Monterrey', 'Puebla', 'Tijuana', 'León', 'Ciudad Juárez', 'Torreón', 'San Luis Potosí', 'Querétaro', 'Mérida', 'Aguascalientes', 'Mexicali', 'Morelia', 'Culiacán', 'Hermosillo', 'Acapulco', 'Veracruz', 'Chihuahua', 'Saltillo', 'Cancún', 'Tampico', 'Toluca', 'Oaxaca'],
  MY: ['Kuala Lumpur', 'George Town', 'Ipoh', 'Shah Alam', 'Petaling Jaya', 'Johor Bahru', 'Kota Kinabalu', 'Kuching', 'Malacca', 'Subang Jaya', 'Klang', 'Ampang Jaya', 'Iskandar Puteri', 'Seremban', 'Sandakan'],
  MZ: ['Maputo', 'Matola', 'Beira', 'Nampula', 'Quelimane'],
  NA: ['Windhoek', 'Rundu', 'Walvis Bay', 'Oshakati'],
  NE: ['Niamey', 'Zinder', 'Maradi', 'Agadez'],
  NG: ['Lagos', 'Kano', 'Ibadan', 'Kaduna', 'Port Harcourt', 'Benin City', 'Maiduguri', 'Zaria', 'Aba', 'Jos', 'Ilorin', 'Oyo', 'Enugu', 'Abeokuta', 'Abuja', 'Onitsha', 'Warri'],
  NI: ['Managua', 'León', 'Masaya', 'Matagalpa', 'Chinandega'],
  NL: ['Amsterdam', 'Rotterdam', 'The Hague', 'Utrecht', 'Eindhoven', 'Tilburg', 'Groningen', 'Almere', 'Breda', 'Nijmegen', 'Enschede', 'Haarlem', 'Arnhem', 'Zaanstad', 'Amersfoort', 'Apeldoorn', 'Dordrecht', 'Leiden', 'Maastricht', 'Zoetermeer'],
  NO: ['Oslo', 'Bergen', 'Stavanger', 'Trondheim', 'Drammen', 'Fredrikstad', 'Kristiansand', 'Sandnes', 'Tromsø', 'Sarpsborg'],
  NP: ['Kathmandu', 'Pokhara', 'Lalitpur', 'Bharatpur', 'Biratnagar', 'Birgunj'],
  NR: ['Yaren'],
  NZ: ['Auckland', 'Wellington', 'Christchurch', 'Hamilton', 'Tauranga', 'Napier', 'Dunedin', 'Palmerston North', 'Nelson', 'Rotorua'],
  OM: ['Muscat', 'Seeb', 'Salalah', 'Sohar', 'Nizwa'],
  PA: ['Panama City', 'San Miguelito', 'Tocumen', 'La Chorrera', 'David'],
  PE: ['Lima', 'Arequipa', 'Trujillo', 'Chiclayo', 'Piura', 'Iquitos', 'Cusco', 'Chimbote', 'Huancayo', 'Tacna'],
  PG: ['Port Moresby', 'Lae', 'Mount Hagen', 'Madang'],
  PH: ['Manila', 'Quezon City', 'Davao City', 'Caloocan', 'Zamboanga City', 'Cebu City', 'Antipolo', 'Pasig', 'Taguig', 'Valenzuela', 'Cagayan de Oro', 'Makati', 'Dasmariñas', 'Las Piñas', 'General Santos', 'Malabon', 'Parañaque'],
  PK: ['Karachi', 'Lahore', 'Faisalabad', 'Rawalpindi', 'Gujranwala', 'Peshawar', 'Multan', 'Islamabad', 'Hyderabad', 'Quetta', 'Bahawalpur', 'Sargodha', 'Sialkot'],
  PL: ['Warsaw', 'Kraków', 'Łódź', 'Wrocław', 'Poznań', 'Gdańsk', 'Szczecin', 'Bydgoszcz', 'Lublin', 'Katowice', 'Białystok', 'Gdynia', 'Częstochowa', 'Radom', 'Sosnowiec', 'Toruń', 'Kielce', 'Gliwice', 'Zabrze', 'Bytom', 'Rzeszów', 'Olsztyn'],
  PT: ['Lisbon', 'Porto', 'Braga', 'Amadora', 'Setúbal', 'Coimbra', 'Funchal', 'Almada', 'Agualva-Cacém', 'Queluz', 'Faro', 'Évora', 'Guimarães', 'Leiria'],
  PW: ['Ngerulmud', 'Koror'],
  PY: ['Asunción', 'Ciudad del Este', 'Luque', 'San Lorenzo', 'Capiatá', 'Lambaré'],
  QA: ['Doha', 'Al Rayyan', 'Al Wakrah', 'Al Khor'],
  RO: ['Bucharest', 'Cluj-Napoca', 'Timișoara', 'Iași', 'Constanța', 'Craiova', 'Brașov', 'Galați', 'Ploiești', 'Oradea', 'Brăila', 'Arad', 'Bacău', 'Pitești', 'Sibiu'],
  RS: ['Belgrade', 'Novi Sad', 'Niš', 'Kragujevac', 'Subotica', 'Zrenjanin'],
  RU: ['Moscow', 'Saint Petersburg', 'Novosibirsk', 'Yekaterinburg', 'Nizhny Novgorod', 'Kazan', 'Chelyabinsk', 'Omsk', 'Samara', 'Ufa', 'Rostov-on-Don', 'Krasnoyarsk', 'Saratov', 'Tolyatti', 'Perm', 'Volgograd', 'Ulyanovsk', 'Barnaul', 'Irkutsk', 'Vladivostok', 'Krasnodar', 'Yaroslavl', 'Khabarovsk', 'Izhevsk', 'Tyumen', 'Voronezh', 'Kemerovo', 'Astrakhan', 'Tomsk', 'Penza'],
  RW: ['Kigali', 'Butare', 'Gitarama'],
  SA: ['Riyadh', 'Jeddah', 'Mecca', 'Medina', 'Dammam', 'Khobar', 'Tabuk', 'Abha', 'Qatif', 'Buraidah', 'Khamis Mushait', 'Al Hofuf', 'Ha\'il', 'Najran'],
  SB: ['Honiara', 'Gizo'],
  SC: ['Victoria'],
  SD: ['Khartoum', 'Omdurman', 'Port Sudan', 'Kassala', 'El Obeid'],
  SE: ['Stockholm', 'Gothenburg', 'Malmö', 'Uppsala', 'Linköping', 'Västerås', 'Örebro', 'Norrköping', 'Helsingborg', 'Jönköping', 'Umeå', 'Lund', 'Borås', 'Sundsvall', 'Gävle', 'Södertälje'],
  SG: ['Singapore'],
  SI: ['Ljubljana', 'Maribor', 'Celje', 'Kranj', 'Velenje', 'Koper'],
  SK: ['Bratislava', 'Košice', 'Prešov', 'Žilina', 'Banská Bystrica', 'Nitra', 'Trnava'],
  SL: ['Freetown', 'Bo', 'Kenema'],
  SM: ['San Marino', 'Serravalle'],
  SN: ['Dakar', 'Pikine', 'Thiès', 'Saint-Louis', 'Kaolack'],
  SO: ['Mogadishu', 'Hargeisa', 'Bosaso', 'Kismayo'],
  SR: ['Paramaribo', 'Lelydorp'],
  SS: ['Juba', 'Malakal', 'Wau'],
  ST: ['São Tomé', 'Santo António'],
  SV: ['San Salvador', 'Soyapango', 'San Miguel', 'Santa Ana', 'Mejicanos'],
  SY: ['Damascus', 'Aleppo', 'Homs', 'Latakia', 'Hama', 'Deir ez-Zor'],
  SZ: ['Mbabane', 'Manzini'],
  TD: ['N\'Djamena', 'Moundou', 'Sarh'],
  TG: ['Lomé', 'Sokodé', 'Kara'],
  TH: ['Bangkok', 'Nonthaburi', 'Pak Kret', 'Hat Yai', 'Udon Thani', 'Chon Buri', 'Nakhon Ratchasima', 'Chiang Mai', 'Pak Kret', 'Rayong', 'Phuket', 'Khon Kaen'],
  TJ: ['Dushanbe', 'Khujand', 'Kulob'],
  TL: ['Dili', 'Baucau'],
  TM: ['Ashgabat', 'Türkmenabat', 'Daşoguz'],
  TN: ['Tunis', 'Sfax', 'Sousse', 'Ettadhamen', 'Kairouan', 'Bizerte', 'Gabès', 'Ariana', 'Gafsa'],
  TO: ['Nuku\'alofa'],
  TR: ['Istanbul', 'Ankara', 'Izmir', 'Bursa', 'Adana', 'Gaziantep', 'Konya', 'Antalya', 'Kayseri', 'Mersin', 'Eskişehir', 'Diyarbakır', 'Samsun', 'Denizli', 'Şanlıurfa', 'Adapazarı', 'Malatya', 'Kahramanmaraş', 'Trabzon', 'Erzurum', 'Van', 'Batman'],
  TT: ['Port of Spain', 'Chaguanas', 'San Fernando'],
  TV: ['Funafuti'],
  TW: ['Taipei', 'Kaohsiung', 'Taichung', 'Tainan', 'Banqiao', 'Zhongli', 'Hsinchu', 'Keelung', 'Taoyuan'],
  TZ: ['Dar es Salaam', 'Mwanza', 'Arusha', 'Dodoma', 'Mbeya', 'Morogoro', 'Zanzibar City'],
  UA: ['Kyiv', 'Kharkiv', 'Odesa', 'Dnipro', 'Donetsk', 'Zaporizhzhia', 'Lviv', 'Kryvyi Rih', 'Mykolaiv', 'Mariupol', 'Luhansk', 'Vinnytsia', 'Makiivka', 'Simferopol', 'Chernivtsi', 'Poltava', 'Kherson', 'Khmelnytskyi', 'Zhytomyr', 'Sumy', 'Cherkasy', 'Chernihiv', 'Rivne', 'Ivano-Frankivsk', 'Ternopil'],
  UG: ['Kampala', 'Gulu', 'Lira', 'Mbarara', 'Jinja'],
  US: ['New York', 'Los Angeles', 'Chicago', 'Houston', 'Phoenix', 'Philadelphia', 'San Antonio', 'San Diego', 'Dallas', 'San Jose', 'Austin', 'Jacksonville', 'Fort Worth', 'Columbus', 'Charlotte', 'Indianapolis', 'San Francisco', 'Seattle', 'Denver', 'Nashville', 'Oklahoma City', 'El Paso', 'Washington DC', 'Las Vegas', 'Louisville', 'Memphis', 'Portland', 'Baltimore', 'Milwaukee', 'Albuquerque', 'Tucson', 'Fresno', 'Sacramento', 'Kansas City', 'Mesa', 'Atlanta', 'Omaha', 'Colorado Springs', 'Raleigh', 'Long Beach', 'Virginia Beach', 'Miami', 'Minneapolis', 'Tampa', 'New Orleans', 'Arlington', 'Bakersfield', 'Honolulu', 'Anaheim', 'Aurora', 'Santa Ana', 'Corpus Christi', 'Riverside', 'St. Louis', 'Pittsburgh', 'Cincinnati', 'Anchorage', 'Lexington', 'Stockton', 'St. Paul', 'Toledo', 'Greensboro', 'Newark', 'Cleveland', 'Buffalo', 'Detroit', 'Boston'],
  UY: ['Montevideo', 'Salto', 'Ciudad de la Costa', 'Paysandú', 'Las Piedras'],
  UZ: ['Tashkent', 'Namangan', 'Samarkand', 'Andijan', 'Nukus', 'Bukhara', 'Fergana'],
  VC: ['Kingstown'],
  VE: ['Caracas', 'Maracaibo', 'Valencia', 'Barquisimeto', 'Maracay', 'Ciudad Guayana', 'Barcelona', 'Maturín', 'Petare', 'Cumana'],
  VN: ['Ho Chi Minh City', 'Hanoi', 'Da Nang', 'Haiphong', 'Can Tho', 'Bien Hoa', 'Hue', 'Nha Trang', 'Buon Ma Thuot', 'Vung Tau', 'Qui Nhon', 'Long Xuyen'],
  VU: ['Port Vila', 'Luganville'],
  WS: ['Apia'],
  YE: ['Sanaa', 'Aden', 'Taiz', 'Al Hudaydah', 'Ibb', 'Dhamar'],
  ZA: ['Johannesburg', 'Cape Town', 'Durban', 'Pretoria', 'Port Elizabeth', 'Pietermaritzburg', 'Bloemfontein', 'East London', 'Nelspruit', 'Kimberley', 'Polokwane', 'Soweto', 'Benoni', 'Tembisa', 'Vereeniging', 'George', 'Rustenburg'],
  ZM: ['Lusaka', 'Ndola', 'Kitwe', 'Kabwe', 'Livingstone'],
  ZW: ['Harare', 'Bulawayo', 'Chitungwiza', 'Mutare', 'Gweru'],
};

/**
 * Get the sorted city list for a given country code.
 * Returns an empty array if the country is not in the list.
 */
export function citiesForCountry(countryCode) {
  if (!countryCode) return [];
  return CITIES_BY_COUNTRY[countryCode.toUpperCase()] ?? [];
}
